<?php
$this->headMeta()
     ->appendHttpEquiv('Content-Type', 'text/html; charset=' . $this->getEncoding());

$this->headLink()
     ->prependStylesheet('http://yui.yahooapis.com/2.5.2/build/base/base-min.css')
     ->prependStylesheet('http://yui.yahooapis.com/2.5.2/build/reset-fonts-grids/reset-fonts-grids.css');

$this->headScript()
     ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js');

echo $this->doctype();

$this->headScript()->captureStart();
?>
var basePath = '<?php echo $this->basePath(); ?>';
var baseUrl = '<?php echo $this->baseUrl(); ?>';
<?php $this->headScript()->captureEnd(); ?>

<html>
    <head>
<?php echo $this->headTitle(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->headLink(); ?>

<?php echo $this->headScript(); ?>

<?php echo $this->headStyle(); ?>

    </head>
    <body>

<?php echo $this->layout()->content; ?>

    </body>
</html>
