<?php
/**
 * Pagination partial
 *
 * @param   integer     $current_page   The current page being displayed.
 * @param   integer     $total_pages    The total number of pages.
 * @param   integer     $show_pages     (OPTIONAL) Number of pages to be
 *                                      displayed above and below the current
 *                                      page.
 */

if ($this->show_pages) {
    $starting_page = max(
        1,
        $this->current_page - $this->show_pages
    );
    $end_page = min(
        $this->total_pages,
        $this->total_pages - $this->show_pages
    );
} else {
    $starting_page = 1;
    $ending_page   = $this->total_pages;
}
?>

<ol class="pagination">

<?php if ($this->current_page != 1): ?>
    <li class="first"><a href="<?php echo $this->url(array('page' => 1)); ?>">First</a></li>
    <li class="previous"><a href="<?php echo $this->url(array('page' => $this->current_page - 1)); ?>">Previous</a></li>
<?php else: ?>
    <li class="first disabled">First</li>
    <li class="previous disabled">Previous</li>
<?php endif; ?>

<?php for ($i = $starting_page; $i <= $ending_page; ++$i): ?>
<?php if ($this->current_page == $i): ?>
    <li class="current_page"><?php echo $i; ?></li>
<?php else: ?>
    <li><a href="<?php echo $this->url(array('page' => $i)); ?>"><?php echo $i; ?></a></li>
<?php endif; ?>
<?php endfor; ?>

<?php if ($this->current_page != $this->total_pages): ?>
    <li class="next"><a href="<?php echo $this->url(array('page' => $this->current_page + 1)); ?>">Next</a></li>
    <li class="last"><a href="<?php echo $this->url(array('page' => $this->total_pages)); ?>">Last</a></li>
<?php else: ?>
    <li class="next disabled">Next</li>
    <li class="last disabled">Last</li>
<?php endif; ?>

</ol>
