<?php if ($this->totalPages > 1): ?>
<p class="pagination">

<?php if ($this->currentPage > 1): ?>
    <span class="first"><a href="<?php echo $this->url(array('page' => 1)); ?>"><?php echo $this->firstText; ?></a></span>
    <span class="previous"><a href="<?php echo $this->url(array('page' => $this->currentPage - 1)); ?>"><?php echo $this->previousText; ?></a></span>
<?php else: ?>
    <span class="first disabled"><?php echo $this->firstText; ?></span>
    <span class="previous disabled"><?php echo $this->previousText; ?></span>
<?php endif; ?>

<?php for ($i = $this->startPage; $i <= $this->lastPage; ++$i): ?>
    <?php if ($i == $this->currentPage): ?>
    <span class="current_page disabled"><?php echo $i; ?></span>
    <?php else: ?>
    <a href="<?php echo $this->url(array('page' => $i)); ?>"><?php echo $i; ?></a>
    <?php endif; ?>
<?php endfor; ?>

<?php if ($this->currentPage < $this->totalPages): ?>
    <span class="next"><a href="<?php echo $this->url(array('page' => $this->currentPage + 1)); ?>"><?php echo $this->nextText; ?></a></span>
    <span class="last"><a href="<?php echo $this->url(array('page' => $this->totalPages)); ?>"><?php echo $this->lastText; ?></a></span>
<?php else: ?>
    <span class="next disabled"><?php echo $this->nextText; ?></span>
    <span class="last disabled"><?php echo $this->lastText; ?></span>
<?php endif; ?>

</p>
<?php endif; ?>
