<?php
$this->headMeta()
     ->appendHttpEquiv('Content-Type', 'text/html; charset=' . $this->getEncoding());

$this->headLink()
     ->prependStylesheet($this->baseUrl() . '/styles/global.css')
     ->prependStylesheet($this->baseUrl() . '/styles/base-min.css')
     ->prependStylesheet($this->baseUrl() . '/styles/reset-fonts-grids.css');

$this->headScript()
     ->prependFile($this->baseUrl() . '/scripts/global.js')
     ->prependFile($this->baseUrl() . '/scripts/jquery-1.2.3.min.js');

echo $this->doctype('XHTML1_STRICT');
?>
<?php $this->headScript()->captureStart(); ?>
var baseUrl = '<?php echo $this->baseUrl(); ?>';
<?php $this->headScript()->captureEnd(); ?>

<html>
    <head>
<?php echo $this->headTitle(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->headLink(); ?>

<?php echo $this->headScript(); ?>

<?php echo $this->headStyle(); ?>

    </head>
    <body>

<?php echo $this->layout()->content; ?>

    </body>
</html>
