<?php
$this->headMeta()
     ->appendHttpEquiv('Content-Type', 'text/html; charset=' . $this->getEncoding());

$this->headLink()
     ->appendStylesheet($this->baseUrl() . '/styles/reset-fonts-grids.css')
     ->appendStylesheet($this->baseUrl() . '/styles/base-min.css')
     ->appendStylesheet($this->baseUrl() . '/styles/site.css');

$this->headScript()
     ->appendFile($this->baseUrl() . '/scripts/jquery-1.2.3.min.js')
     ->appendFile($this->baseUrl() . '/scripts/site.js');

echo $this->doctype('XHTML1_STRICT');
?>

<html>
    <head>
<?php echo $this->headTitle(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->headLink(); ?>

<?php echo $this->headScript(); ?>

    </head>
    <body>

<?php echo $this->layout()->content; ?>

    </body>
</html>
