<?php
if($this->errors):
    $this->headScript()
         ->appendFile($this->baseUrl() . '/facebox/facebox.js')
         ->appendFile($this->baseUrl() . '/scripts/debug.js');

    $this->headLink()
         ->appendStylesheet($this->baseUrl() . '/facebox/facebox.css')
         ->appendStylesheet($this->baseUrl() . '/styles/debug.css');
?>
<div id="debug_summary">
    <h2><?php echo $this->errors->exception->getMessage(); ?></h2>
    <div id="debug_complete">
        <h3>Message</h3>
        <textarea><?php echo $this->errors->exception; ?></textarea>

        <h3>Complete Stack Trace</h3>
        <textarea><?php print_r($this->errors->exception->getTrace()); ?></textarea>
    </div>
</div>
<?php endif; ?>
