<?php if($this->errors): ?>
<div id="debug">
    <h2><?php echo $this->errors->exception->getMessage(); ?></h2>
    <p>(Click here to show/hide the exception)</p>
    <div class="exception">
        <h3>Message</h3>
        <pre><?php echo $this->errors->exception; ?></pre>

        <h3>Complete Stack Trace</h3>
        <pre><?php print_r($this->errors->exception->getTrace()); ?></pre>
    </div>
</div>
<?php endif; ?>
