<?php
$this->headMeta()
     ->appendHttpEquiv("Content-Type", "text/html; charset={$this->getEncoding()}");

echo $this->doctype();

$this->headScript()->captureStart();
?>
var basePath = "<?php echo $this->basePath(); ?>";
var baseUrl  = "<?php echo $this->baseUrl(); ?>";
<?php $this->headScript()->captureEnd(); ?>

<html>
    <head>
<?php echo $this->headTitle(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->headLink(); ?>

<?php echo $this->headScript(); ?>

<?php echo $this->headStyle(); ?>

    </head>
    <body>

<?php echo $this->layout()->content; ?>

    </body>
</html>
